Був присутній на парі

In [ ]:
import numpy as np
det = np.linalg.det(matrix)
det
np.float64(-34.00000000000001)

np.__version__

'2.0.2'

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[3, 5, 2],
       [4, 3, 5],
       [5, 3, 5]])

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(18.999999999999996)

Чтобы изменить содержимое ячейки, дважды нажмите на нее (или выберите "Ввод")

In [ ]:
product = np.prod(matrix)
product

np.int64(135000)

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(18.999999999999996)

In [ ]:
product = np.prod(matrix)
product

np.int64(135000)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1 * prod_2 * prod_3


np.int64(135000)

In [ ]:
np.sum(matrix)


np.int64(35)

In [ ]:
np.max(matrix)

np.int64(5)

In [ ]:
np.min(matrix)

np.int64(2)

In [ ]:
np.mean(matrix)

np.float64(3.888888888888889)

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)


Матриця квадратних коренів:
[[1.73205081 2.23606798 1.41421356]
 [2.         1.73205081 2.23606798]
 [2.23606798 1.73205081 2.23606798]]


In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)


Сума елементів кожного рядка:
[[10]
 [12]
 [13]]


In [ ]:
matrix.sum(axis=1).reshape(-1, 1)

array([[10],
       [12],
       [13]])

In [ ]:
x = np.matrix([[1, 2], [4, 3]])
x


matrix([[1, 2],
        [4, 3]])

In [ ]:
vector = np.random.randint(0, 10, size=25)
vector

array([9, 3, 2, 8, 8, 8, 7, 5, 7, 5, 2, 5, 8, 3, 9, 6, 9, 6, 0, 2, 1, 9,
       7, 7, 8])

In [ ]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 9, 9, 8, 8, 8, 8, 8, 7, 7, 7, 7, 6, 6, 5, 5, 5, 3, 3, 2, 2,
       2, 1, 0])

In [ ]:
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)

In [ ]:
from scipy import stats
import numpy as np
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[10  8  1  8]
 [ 7  2  2  4]
 [ 5  4  7  7]
 [ 8  4  9  5]]

Матриця 2:
[[ 8  5  7  6]
 [ 8  1 10  8]
 [ 8  8  7  3]
 [ 2  8  6  9]]


In [ ]:
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2 != 0))
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)



Сума матриць:
[[18 13  8 14]
 [15  3 12 12]
 [13 12 14 10]
 [10 12 15 14]]

Різниця матриць:
[[ 2  3 -6  2]
 [-1  1 -8 -4]
 [-3 -4  0  4]
 [ 6 -4  3 -4]]

Поелементний добуток матриць:
[[80 40  7 48]
 [56  2 20 32]
 [40 32 49 21]
 [16 32 54 45]]


In [ ]:
x = np.arange(9.)
x


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.)
x2

array([0., 1., 2.])

In [ ]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
x1 = np.arange(6)
x1


array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x2

array([1, 2, 3, 3, 2, 1])

In [ ]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

In [ ]:
np.power(x1, x2)

array([ 0,  1,  8, 27, 16,  5])